buildscript: scripts/deploy
postinstall: scripts/postinstall.sh
user: www-data
pip:
 - genshi
 - gunicorn
 - device-proxy
dependencies:
 - postgresql-common
 - libjpeg-dev
 - zlib1g-dev
 - memcached
 - libxslt1-dev
 - libproj0
 - libproj-dev
 - libgdal1-dev
 - libgeoip1
 - libgeoip-dev
 - postgis
